data:
  partitions:
    train:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: train
        rating_threshold: 4
    val:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: train
        rating_threshold: 4
  dataloader:
    batch_size: 10
    num_workers: 2
    pin_memory: true

model:
  name: BaselineModel
  params:
    n_feats: 1024
    fc_hidden: 512
    n_class: 10

optimizer:
  name: Adam
  params:
    lr: 3.0e-4

metrics:
  device: auto
  train: []
  inference: []

trainer:
  device: auto
  seed: 1
  n_epochs: 10
  epoch_len: null
  log_step: 50
  save_period: 5
  save_dir: ./saved/default
  tb_dir: ./runs/default
  device_tensors: [data_object, labels]
  loss_names: [loss]
  max_grad_norm: null
