data:
  partitions:
    train:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: train
        max_history_size: 200
        split_strategy: "leave_one_out"
    val:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: val
        max_history_size: 200
        split_strategy: "leave_one_out"
  dataloader:
    batch_size: 128
    num_workers: 2
    pin_memory: true

model:
  name: SASRec
  params:
    item_count: 3707
    embedding_dim: 50
    max_history_size: 200
    attn_dropout: 0.2

optimizer:
  name: Adam
  params:
    lr: 1e-3

metrics:
  device: auto
  train: []
  inference:
    - name: Hitrate
      params:
        alias: "hitrate_full@50"
        k: 50
        last_only: true
        filter_history: false
    - name: Hitrate
      params:
        alias: "hitrate_full@10"
        k: 10
        last_only: true
        filter_history: false
    - name: Hitrate
      params:
        alias: "hitrate_full@1"
        k: 1
        last_only: true
        filter_history: false

trainer:
  device: auto
  seed: 1
  n_epochs: 100
  epoch_len: null
  log_step: 50
  save_period: 5
  save_dir: ./saved/sasrec
  tb_dir: ./runs/sasrec
  device_tensors: [data_object, labels]
  loss_names: [loss]
  max_grad_norm: null
