data:
  partitions:
    train:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: train
        max_history_size: 200
        split_strategy: "leave_one_out"
    val:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: val
        max_history_size: 200
        split_strategy: "leave_one_out"
  dataloader:
    batch_size: 128
    num_workers: 2
    pin_memory: true

model:
  name: SASRec
  params:
    item_count: 3707
    max_history_size: 200
    embedding_dim: 50
    attn_n_layers: 2
    attn_n_head: 1
    attn_dim_feedforward: 50
    attn_dropout: 0.2
    input_dropout: 0.2
    user_embedding_norm: "layer_norm"
    use_mol: true
    dot_loss_weight: 0.0
    mol:
      dot_product_dimension: 64
      query_groups: 8
      item_groups: 4
      temperature: 0.05
      dot_product_l2_norm: true
      gating_combination_type: "glu_silu"
      eps: 1.0e-6
      autocast_bf16: true
      num_train_negatives: 128
      query_chunk_size: 10000
      softmax_temperature: 1.0
      query_dropout_rate: 0.0
      query_hidden_dim: 512
      uid_embedding_hash_sizes: [6040]
      uid_dropout_rate: 0.5
      item_dropout_rate: 0.1
      item_hidden_dim: 0
      query_nonlinearity: "swiglu"
      item_nonlinearity: "swiglu"
      gating_query_hidden_dim: 128
      gating_item_hidden_dim: 128
      gating_qi_hidden_dim: 128
      gating_query_fn: true
      gating_item_fn: true
      gating_item_dropout_rate: 0.0
      gating_qi_dropout_rate: 0.0
      softmax_dropout_rate: 0.2
    mol_runtime:
      mi_loss_weight: 0.001
      uid_embedding_l2_weight: 0.1
      loss_weight: 1.0

optimizer:
  name: AdamW
  params:
    lr: 1e-3
    weight_decay: 0.0

metrics:
  device: auto
  train: []
  inference:
    - name: Hitrate
      params:
        alias: "hitrate_mol@50"
        k: 50
        last_only: true
        filter_history: false
    - name: Hitrate
      params:
        alias: "hitrate_mol@10"
        k: 10
        last_only: true
        filter_history: false
    - name: Hitrate
      params:
        alias: "hitrate_mol@1"
        k: 1
        last_only: true
        filter_history: false
    - name: MRR
      params:
        alias: "mrr_mol"
        last_only: true
        filter_history: false

trainer:
  device: auto
  seed: 1
  n_epochs: 100
  epoch_len: null
  log_step: 50
  save_period: 5
  save_dir: ./saved/sasrec_mol
  tb_dir: ./runs/sasrec_mol
  device_tensors: [data_object, labels]
  loss_names: [loss]
  max_grad_norm: null
