data:
  partitions:
    train:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: train
        max_history_size: 200
    val:
      name: MovieLensDataset
      params:
        variant: "ml-1m"
        partition: val
        max_history_size: 200
  dataloader:
    batch_size: 128
    num_workers: 2
    pin_memory: true

model:
  name: HSTU
  params:
    item_count: 11649
    max_history_size: 200
    embedding_dim: 50
    attn_dropout: 0.2

optimizer:
  name: AdamW
  params:
    lr: 1e-3

metrics:
  device: auto
  train: []
  inference:
    - name: HitrateFull
      params:
        alias: "hitrate_full@10"
        k: 10
        last_only: true
        filter_history: false
    - name: HitrateFull
      params:
        alias: "hitrate_full@25"
        k: 25
        last_only: true
        filter_history: false
    - name: HitrateFull
      params:
        alias: "hitrate_full@50"
        k: 50
        last_only: true
        filter_history: false

trainer:
  device: auto
  seed: 1
  n_epochs: 100
  epoch_len: null
  log_step: 50
  save_period: 5
  save_dir: ./saved/hstu
  tb_dir: ./runs/hstu
  device_tensors: [data_object, labels]
  loss_names: [loss]
  max_grad_norm: null
